"use client";
import { useState } from "react";
import { useT } from "@/components/LocaleProvider";
import type { ConsultationOffer } from "@/lib/lms-features-db";
export function ConsultationsAdminClient({ initialOffers }: { initialOffers: ConsultationOffer[] }) {
  const t = useT(); const [offers, setOffers] = useState(initialOffers); const [title, setTitle] = useState(""); const [titleAr, setTitleAr] = useState(""); const [price, setPrice] = useState(0); const [error, setError] = useState("");
  async function reload() { const r = await fetch("/api/dashboard/consultations"); const d = await r.json(); if (r.ok) setOffers(d.offers ?? []); }
  async function create() { const r = await fetch("/api/dashboard/consultations", { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, titleAr: titleAr || null, price }) }); if (!r.ok) return setError("Failed to create"); setTitle(""); setTitleAr(""); setPrice(0); await reload(); }
  async function patch(id: string, data: object) { await fetch(`/api/dashboard/consultations/${id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); await reload(); }
  async function remove(id: string) { if (window.confirm(t("common.confirmDelete", "Delete this item?"))) { await fetch(`/api/dashboard/consultations/${id}`, { method: "DELETE", credentials: "include" }); await reload(); } }
  return <div className="space-y-5"><h2 className="text-xl font-bold">{t("consultations.adminTitle", "Consultations")}</h2>{error ? <p className="text-red-600">{error}</p> : null}<div className="flex flex-wrap gap-2 rounded border p-4"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Title" className="rounded border px-3 py-2" /><input value={titleAr} onChange={(e) => setTitleAr(e.target.value)} placeholder="العنوان" className="rounded border px-3 py-2" /><input type="number" value={price} onChange={(e) => setPrice(Number(e.target.value))} className="rounded border px-3 py-2" /><button onClick={() => void create()} className="rounded bg-[var(--color-primary)] px-4 text-white">Create</button></div><div className="space-y-2">{offers.map((offer) => <div key={offer.id} className="flex justify-between rounded border p-4"><span>{offer.titleAr || offer.title} · {offer.price}</span><span className="flex gap-3"><button onClick={() => void patch(offer.id, { isPublished: !offer.isPublished })} className="underline">{offer.isPublished ? "Unpublish" : "Publish"}</button><button onClick={() => void remove(offer.id)} className="text-red-600 underline">Delete</button></span></div>)}</div></div>;
}
