"use client";
import { useMemo, useState } from "react";
import { useT } from "@/components/LocaleProvider";
import type { ForumCategory, ForumThread } from "@/lib/forum-db";
export function ForumAdminClient({ initialCategories, initialThreads }: { initialCategories: ForumCategory[]; initialThreads: ForumThread[] }) {
  const t = useT(), [threads, setThreads] = useState(initialThreads), [query, setQuery] = useState("");
  const filtered = useMemo(() => threads.filter((thread) => `${thread.title} ${thread.body} ${thread.authorName ?? ""}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => +new Date(b.createdAt) - +new Date(a.createdAt)), [threads, query]);
  async function patch(id: string, patch: Record<string, boolean>) { const r = await fetch(`/api/forum/${id}`, { method: "PATCH", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(patch) }); if (r.ok) setThreads((items) => items.map((item) => item.id === id ? { ...item, ...Object.fromEntries(Object.entries(patch).map(([key, value]) => [key === "pinned" ? "isPinned" : "isLocked", value])) } : item)); }
  async function remove(id: string) { if (!window.confirm(t("forum.confirmDelete", "Delete this thread?"))) return; const r = await fetch(`/api/forum/${id}`, { method: "DELETE", credentials: "include" }); if (r.ok) setThreads((items) => items.filter((item) => item.id !== id)); }
  return <div className="space-y-6"><h2 className="text-xl font-bold">{t("forum.adminTitle", "Forum moderation")}</h2><div className="rounded border p-4"><h3 className="font-semibold">{t("forum.categories", "Categories")}</h3><div className="mt-3 flex flex-wrap gap-2">{initialCategories.map((category) => <span key={category.id} className="rounded bg-[var(--color-surface)] px-3 py-1 text-sm">{category.nameAr || category.name}{!category.isVisible ? " · hidden" : ""}</span>)}</div></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder={t("forum.search", "Search threads")} className="w-full rounded border px-3 py-2" /><div className="space-y-3">{filtered.map((thread) => <div key={thread.id} className="rounded border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{thread.title}</h3><p className="text-sm text-[var(--color-muted)]">{thread.categoryName} · {thread.authorName} · {new Date(thread.createdAt).toLocaleString()}</p></div><div className="flex gap-3 text-sm"><button onClick={() => void patch(thread.id, { pinned: !thread.isPinned })} className="underline">{thread.isPinned ? "Unpin" : "Pin"}</button><button onClick={() => void patch(thread.id, { locked: !thread.isLocked })} className="underline">{thread.isLocked ? "Unlock" : "Lock"}</button><button onClick={() => void remove(thread.id)} className="text-red-600 underline">Delete</button></div></div><p className="mt-3 line-clamp-2 text-sm">{thread.body}</p></div>)}</div></div>;
}
